### ISSUE TITLE
Add cd:at-large to states with only one congressional district

### ISSUE THREAD

**Issue by j-ro** [opencivicdata/ocd-division-ids#110]
This may not be the right place for this discussion, but...

I'd like to propose a different handling for OCD IDs for at-large districts. Currently, it seems there is no OCD ID for an at-large district, rather the next highest OCD ID division is used.

For example, Vermont has only one member of Congress, so his OCD ID is `ocd-division/country:us/state:vt`

Whereas, in a state with more than one member, they have divisions like this:

`ocd-division/country:us/state:nc/cd:2`

This makes it hard to regularize data and match between systems. It's easy to match via OCD ID, but in this case, the state level OCD ID is also shared by other elected officials (governors, senators), making matching harder and necessitating special rules for these states.

It would be better if this were handed like the Sunlight API handles them (https://sunlightlabs.github.io/congress/legislators.html), where they assign a district of 0 to at-large districts. So, for Vermont, we'd have `ocd-division/country:us/state:vt/cd:0`

**Comment by jpmckinney** [comment]
`state:vt/cd:at-large` makes sense to me in terms of having a complete set of congressional districts under the `cd` type.

However, at the local government level, there can be dozens of at-large councillors, which requires special handling/logic anyway. In that case, I don't see the value in having an at-large alias.
