### ISSUE TITLE
state geometries?

### ISSUE THREAD

**Issue by dcloud** [opencivicdata/ocd-division-ids#119]
Per our discussion, it appears that *state-level geometries* are not in the API. `ocd-division/country:us/state:nc/` for example.

**Comment by paultag** [comment]
@dcloud did you try it without the trailing slash? That's not a valid ocd-id

**Comment by dcloud** [comment]
The `https://api.opencivicdata.org/<ocd-id>` redirects to a URL with a trailing slash. Using a division id as a URL param to the organizations endpoint results in a 500 error, with or without the trailing slash. As in https://api.opencivicdata.org/organizations/?division_id=ocd-division%2Fcountry%3Aus%2Fstate%3Anc

**Comment by jpmckinney** [comment]
Geometries are not an issue to this repository. I think this issue should be moved to https://github.com/opencivicdata/api.opencivicdata.org
