### ISSUE TITLE
Additional field checking for non-US

### ISSUE THREAD

**Issue by paultag** [opencivicdata/ocd-division-ids#122]
@mileswwatkins just implemented some key value checking stuff in #121 - we added some census fields (which should be globally unique) to validate.

This issue is open for any non-US sets that want the same checking, anyone have fields?

cc/ @jpmckinney

**Comment by jpmckinney** [comment]
I suppose `sgc`, `url`, and `data_catalog` should be globally unique, but there's little change duplicates would be introduced.

**Comment by jpmckinney** [comment]
I've added the Canadian unique fields to `compile.py`.

**Comment by paultag** [comment]
:+1: thanks @jpmckinney :)

Yeah, there's a low chance, but having multiple scripts / files combined makes me skeeved out a bit, so I asked Miles to add it -- up to you to have whatever you want in there!

**Comment by paultag** [comment]
I'll leave this up for a day or so, anyone else should feel free to commit / send in PRs!

**Comment by jpmckinney** [comment]
Yup, definitely worth having, especially if/once the CA scripts start pulling info for the same division from multiple sources.

**Comment by jpmckinney** [comment]
I believe this issue is complete.
