### ISSUE TITLE
data source for local municipal divisions?

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/ocd-division-ids#125]
How were the IDs for the local municipal divisions created? Did this data come from US Census or some place else?

Examples: 
https://github.com/opencivicdata/ocd-division-ids/blob/8b21b8db2efce4f9b38b9bf1397252f7533fdbd9/identifiers/country-us/state-mn-precincts.csv
https://github.com/opencivicdata/ocd-division-ids/blob/8b21b8db2efce4f9b38b9bf1397252f7533fdbd9/identifiers/country-us/state-mn-local_gov.csv

We're starting to collect some of the boundaries for these in a [new repo](https://github.com/datamade/open-divisions), but wanted to double-check we're not duplicating work. It looks like the boundaries for these divisions have not been collected yet for OCD.

cc @jamesturk @paultag

**Comment by jamesturk** [comment]
They're generated from this script https://github.com/opencivicdata/ocd-division-ids/blob/master/scripts/country-us/census_places.py

**Comment by derekeder** [comment]
@jamesturk thanks! I take it Census has the place names but not the geographies, correct?

**Comment by jamesturk** [comment]
I think that's the case, iirc they have counties and msas but not "places"

**Comment by derekeder** [comment]
Looks like they have a 'Places' shapefile, but it is only for city and township boundaries, not wards or precincts: https://www.census.gov/geo/maps-data/data/cbf/cbf_place.html

<img width="1109" alt="screen shot 2015-08-28 at 3 24 03 pm" src="https://cloud.githubusercontent.com/assets/919583/9556233/daf33e44-4d98-11e5-8813-f4df1a313c8e.png">

**Comment by derekeder** [comment]
Think this answers my question. Closing.

**Comment by fgregg** [comment]
Wait? How did info about wards get in there?
