### ISSUE TITLE
Historical; Orleans and Dakota Territories?

### ISSUE THREAD

**Issue by showerst** [opencivicdata/ocd-division-ids#136]
I've been loading some historical US legislative data, and OCD is missing the Territory of Orleans, and the Dakota territory which both sent a few people to congress in the 1800s.
https://en.wikipedia.org/wiki/Territory_of_Orleans
https://en.wikipedia.org/wiki/Dakota_Territory

If I add submit a PR for it, as ocd-division/country:us/territory:ol and ocd-division/country:us/territory:dk with proper start/end dates will you accept it, or is it obscure enough to be out of scope? 

If so, should ol get a same_as with the state of Louisana?

**Comment by jpmckinney** [comment]
That sounds right. Where do the abbreviations ol and dk come from?

**Comment by showerst** [comment]
ol and dk come from https://github.com/unitedstates/congress-legislators -- but could just be arbitrary. Happy to format them however you want.

**Comment by jpmckinney** [comment]
Hmm, if you can find any source to support those abbreviations, that'd be best.

**Comment by showerst** [comment]
I doubt I'll find a good historical source; what's preferable to those abbreviations? I'd rather the identifier fit whatever scheme you use now, since this is such and obscure edge case.

**Comment by jpmckinney** [comment]
`dt` seems much more prevalent, e.g. https://www.archives.gov/publications/prologue/2003/winter/little-town-in-nara-1.html http://www.loc.gov/pictures/item/99613785/

**Comment by showerst** [comment]
Ah cool, and thanks for the cross-links. 

Last question while we're on the subject; the Phillippines also sent a number of reps to the house during their time as a US territory. https://en.wikipedia.org/wiki/Non-voting_members_of_the_United_States_House_of_Representatives#The_Philippines

Is that something we'd create a division for, distinct from the modern country of the Philippines?

**Comment by jpmckinney** [comment]
Like Orleans, we can create `ocd-division/country:us/territory:ph` (taking `ph` from the ISO country code for the Philippines).

**Comment by showerst** [comment]
Cool. Is there a process guide for OCD PRs? Can I just fork it, manually add them to country-us.csv, and create a PR or is there more process to it?

**Comment by jpmckinney** [comment]
country-us.csv is autogenerated from dependent files.

Instead, edit https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-us/us_territories.csv

**Comment by jpmckinney** [comment]
Closed by #137
