### ISSUE TITLE
sameAs semantics question

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/ocd-division-ids#138]
@jamesturk @paultag 

Is the Orleans Territory `sameAs` the state of Louisiana?

**Comment by jamesturk** [comment]
going by https://en.wikipedia.org/wiki/Territory_of_Orleans, I'd say so

**Comment by jpmckinney** [comment]
Ok, so a division's identity survives changes in its classification (organized incorporated territory versus state).
