### ISSUE TITLE
Convert to datapackage

### ISSUE THREAD

**Issue by patcon** [opencivicdata/ocd-division-ids#144]
Would this be a sensible thing to do? Seems like this fits the normal format of scripts + data. Would a PR for this be accepted?

Seems like it might be worth the exercise, as a repo with some many data files would probably bring up pain points in the datapackage toolset worth addressing.

**Comment by jpmckinney** [comment]
Most users just use the single compiled CSV for their country, which is easy to maintain by just downloading the latest version. Perhaps a third-party data package could be maintained?

**Comment by patcon** [comment]
You mean one per country? Or one with all countries, but just the CSVs and metadata?

**Comment by jpmckinney** [comment]
For example, I only use this file: https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-ca.csv

I don't use the individual files in https://github.com/opencivicdata/ocd-division-ids/tree/master/identifiers/country-ca

**Comment by patcon** [comment]
Ah gotcha. But I'll admit that one thing I really liked about the datapackage philosophy was that it seemed to encourage the co-location of the data and the scripts from which the data is massaged/derived. Any preference on that yourself, or are you just as happy to have the data live alone in a datapackage repo?

**Comment by jpmckinney** [comment]
Isn't this repo already in a situation where the scripts and data are collocated? (They are in the same repo.)

**Comment by patcon** [comment]
Def. The original ask was whether it would be worthwhile to add a datapackage.json describing the data :)

But I suppose until this data is in a CKAN portal somewhere, having that metadata isn't much value-add. So I'll just close until such a time. Sorry for the noise on this one
