### ISSUE TITLE
How to handle entities like BART?

### ISSUE THREAD

**Issue by dpassage** [opencivicdata/ocd-division-ids#30]
First, love the work you're doing here. Just the sort of thing I need for some other projects...

My question is how to handle entities like BART, the regional transit authority in the San Francisco Bay Area.

It covers multiple counties, so can be defined in terms of the boundaries of those counties. Its board is directly elected from equal-population districts, which of necessity have boundaries which cross county lines. So in a hierarchy, it's below the state, above the county.

But then you have entities like Colorado's Regional Transportation District (RTD), which has an elected board, but whose boundaries are not coterminous with the counties it serves.

**Comment by nealmcb** [comment]
Interesting case.  And I'm guessing that there are other such entities that cross state and even country boundaries.  Aren't districts fun :)
